#日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml


spring:
#视图解析器
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
  resources: #直接访问springboot下的静态资源
    static-locations: classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
#数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/library_system?serverTimezone=GMT%2B8
    username: root
    password: 346545
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#shiro的首页路径
shiro:
  loginUrl: /login/login
